config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :students
  resources :talents

  root 'talents#index'
  

end

app/models/student.rb
class Student < ActiveRecord::Base
	has_and_belongs_to_many :talents
	def to_label
    	"#{name} (#{email})"
	end
end

app/models/talent.rb
class Talent < ActiveRecord::Base
	has_and_belongs_to_many :students
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :email, :talent_ids => [])
    end
end

app/controllers/talents_controller.rb
class TalentsController < ApplicationController
  before_action :set_talent, only: [:show, :edit, :update, :destroy]

  # GET /talents
  # GET /talents.json
  def index
    @talents = Talent.all
  end

  # GET /talents/1
  # GET /talents/1.json
  def show
  end

  # GET /talents/new
  def new
    @talent = Talent.new
  end

  # GET /talents/1/edit
  def edit
  end

  # POST /talents
  # POST /talents.json
  def create
    @talent = Talent.new(talent_params)

    respond_to do |format|
      if @talent.save
        format.html { redirect_to @talent, notice: 'Talent was successfully created.' }
        format.json { render :show, status: :created, location: @talent }
      else
        format.html { render :new }
        format.json { render json: @talent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /talents/1
  # PATCH/PUT /talents/1.json
  def update
    respond_to do |format|
      if @talent.update(talent_params)
        format.html { redirect_to @talent, notice: 'Talent was successfully updated.' }
        format.json { render :show, status: :ok, location: @talent }
      else
        format.html { render :edit }
        format.json { render json: @talent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /talents/1
  # DELETE /talents/1.json
  def destroy
    @talent.destroy
    respond_to do |format|
      format.html { redirect_to talents_url, notice: 'Talent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_talent
      @talent = Talent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def talent_params
      params.require(:talent).permit(:name, :student_ids => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/talents_helper.rb
module TalentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TEAMSaturn</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<%= yield %>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">CI Talents</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Talents', talents_path %></li>
	<li><%= link_to 'Students', students_path %></li>
        <li><%= link_to 'Create Talent', new_talent_path %></li>
        <li><%= link_to 'New Student', new_student_path %></li>
      </ul>
    </div>
  </div>
</nav>
<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Students</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">CI Talents</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Talents', talents_path %></li>
	<li><%= link_to 'Students', students_path %></li>
        <li><%= link_to 'Create Talent', new_talent_path %></li>
        <li><%= link_to 'New Student', new_student_path %></li>
      </ul>
    </div>
  </div>
</nav>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.email %></td>
	<td><%= link_to ' Show ', student %></td> 
        <td><%= link_to 'Edit ', edit_student_path(student) %></td> 
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/students/new.html.erb
<h1>New Student</h1>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">CI Talents</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Talents', talents_path %></li>
	<li><%= link_to 'Students', students_path %></li>
        <li><%= link_to 'Create Talent', new_talent_path %></li>
        <li><%= link_to 'New Student', new_student_path %></li>
      </ul>
    </div>
  </div>
</nav>
<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">CI Talents</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Talents', talents_path %></li>
	<li><%= link_to 'Students', students_path %></li>
        <li><%= link_to 'Create Talent', new_talent_path %></li>
        <li><%= link_to 'New Student', new_student_path %></li>
      </ul>
    </div>
  </div>
</nav>
<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/talents/_form.html.erb
<%= simple_form_for(@talent) do |f| %>
  <% if @talent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@talent.errors.count, "error") %> prohibited this talent from being saved:</h2>

      <ul>
      <% @talent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.association :students %>
  <%= f.button :submit %>
<% end %>

app/views/talents/edit.html.erb
<h1>Editing Talent</h1>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">CI Talents</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Talents', talents_path %></li>
	<li><%= link_to 'Students', students_path %></li>
        <li><%= link_to 'Create Talent', new_talent_path %></li>
        <li><%= link_to 'New Student', new_student_path %></li>
      </ul>
    </div>
  </div>
</nav>
<%= render 'form' %>

<%= link_to 'Show', @talent %> |
<%= link_to 'Back', talents_path %>

app/views/talents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Talents</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">CI Talents</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Talents', talents_path %></li>
	<li><%= link_to 'Students', students_path %></li>
        <li><%= link_to 'Create Talent', new_talent_path %></li>
        <li><%= link_to 'New Student', new_student_path %></li>
      </ul>
    </div>
  </div>
</nav>
    <% @talents.each do |talent| %>
      <tr>
        <td><%= talent.name %></td>
        <td><%= link_to ' Show ', talent %></td> 
	<td><%= link_to 'Edit ', edit_talent_path(talent) %></td> 
	<td><%= link_to 'Destroy', talent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/talents/new.html.erb
<h1>New Talent</h1>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">CI Talents</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Talents', talents_path %></li>
	<li><%= link_to 'Students', students_path %></li>
        <li><%= link_to 'Create Talent', new_talent_path %></li>
        <li><%= link_to 'New Student', new_student_path %></li>
      </ul>
    </div>
  </div>
</nav>
<%= render 'form' %>

<%= link_to 'Back', talents_path %>

app/views/talents/show.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">CI Talents</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Talents', talents_path %></li>
	<li><%= link_to 'Students', students_path %></li>
        <li><%= link_to 'Create Talent', new_talent_path %></li>
        <li><%= link_to 'New Student', new_student_path %></li>
      </ul>
    </div>
  </div>
</nav>
<p>
  <strong>Name:</strong>
  <%= @talent.name %>
</p>

    <p>
      <b>Who has this talent?</b>
      <%= @talent.students.map {|x| x.to_label}.join ', ' %>
    </p>

<%= link_to 'Edit', edit_talent_path(@talent) %> |
<%= link_to 'Back', talents_path %>